### ISSUE TITLE
GitHub Education Bot missing PR reviews

### ISSUE THREAD

**Issue by JackW-Dev** [education/GitHubGraduation-2021#479] opened 2021-05-12 09:47 UTC
GitHub-Education-Bot appears to be skipping over/ missing some PRs and when flagged for review manually is still not reviewing the content.
Unsure why this may be as it appears to be reviewing other PRs posted around a similar time.

**Comment by aravindvnair99** [comment] 2021-05-12 09:50
@JackW-Dev You need to request a review.

**Comment by JackW-Dev** [comment] 2021-05-12 09:52
@aravindvnair99 Hi! A review was manually requested by a member of staff over 9 hours ago yet the bot is still showing as pending review.

**Comment by aravindvnair99** [comment] 2021-05-12 09:53
@JackW-Dev Can you give a link to your PR?

**Comment by JackW-Dev** [comment] 2021-05-12 09:54
@aravindvnair99 https://github.com/education/GitHubGraduation-2021/pull/47

**Comment by aravindvnair99** [comment] 2021-05-12 09:56
> @aravindvnair99 #47

![image](https://user-images.githubusercontent.com/22199259/117956069-51fbe280-b336-11eb-8fb3-989f3bce85d4.png)

@JackW-Dev The bot did check and your PR is good to go. You seem to be missing the label though.

**Comment by JackW-Dev** [comment] 2021-05-12 09:58
@aravindvnair99 If you check the right side bar you can see that a review is still awaiting though and that no approval message has been provided like in other PRs.

**Comment by aravindvnair99** [comment] 2021-05-12 09:59
I noticed you have 2 other PRs:

- https://github.com/education/GitHubGraduation-2021/pull/41 also passed checks
- https://github.com/education/GitHubGraduation-2021/pull/32 one commit passed checks. And one for which the check didn't run.

@JackW-Dev I would recommend you make a fresh PR after deleting your fork. The bot seems to be working fine now as I just made a PR and so did several others.

**Comment by JackW-Dev** [comment] 2021-05-12 10:04
@aravindvnair99 Yes, the other PRs were made and encountered the same error.
The bot was also consistently approving and labeling PRs around the time of mine but for some reason not labeling mine.
I did notice a few other users still appear to have this issue. I will close and resubmit a fresh PR in hopes of it working.
Hopefully those who are encountering the same issue can also recieve support in correcting this.

**Comment by aravindvnair99** [comment] 2021-05-12 10:05
> @aravindvnair99 If you check the right side bar you can see that a review is still awaiting though and that no approval message has been provided like in other PRs.

@JackW-Dev Yes, it's because of the error as you can see here: https://github.com/education/GitHubGraduation-2021/pull/47/checks?check_run_id=2561487742

![image](https://user-images.githubusercontent.com/22199259/117957163-668caa80-b337-11eb-805b-7a88e9513fca.png)

Your quote is longer than 100 characters. It's 116. Shorten it to less than 100.

**Comment by JackW-Dev** [comment] 2021-05-12 10:07
@aravindvnair99 Ahh okay, I will change it and try again now then. Fingers crossed haha!

**Comment by aravindvnair99** [comment] 2021-05-12 10:08
@elisemoe The check should actually be failing when the characters are more. We have a bug here as the check is passing and the user isn't notified. The exit code isn't set correctly.

**Comment by aravindvnair99** [comment] 2021-05-12 10:10
> @aravindvnair99 Ahh okay, I will change it and try again now then. Fingers crossed haha!

@JackW-Dev It should work. Just make sure to follow the rules mentioned in the README:

```Markdown
---
name: FULLNAME-OR-NICKNAME # No longer than 28 characters
institution: INSTITUTION-NAME 🚩 # no longer than 58 characters
quote: YOUR-SENIOR-QUOTE # no longer than 100 characters, avoid using quotes(") to guarantee the format remains the same.
github_user: YOUR-GITHUB-USERNAME
---
```

**Comment by JackW-Dev** [comment] 2021-05-12 10:11
@aravindvnair99 Just submitted a fresh one and it has worked! Thanks for the help.
Unsure why the bot isn't flagging this length error though, could do with a fix ideally.

**Comment by aravindvnair99** [comment] 2021-05-12 10:18
> @aravindvnair99 Just submitted a fresh one and it has worked! Thanks for the help.
> Unsure why the bot isn't flagging this length error though, could do with a fix ideally.

@JackW-Dev Glad it worked. The problem is here:

https://github.com/education/GitHubGraduation-2021/blob/ac75fdb3f3aa68b5a2dd2338347023e5e4828127/.github/workflows/src/index.js#L54-L56

```console
(node:2461) UnhandledPromiseRejectionWarning: TypeError: errors is not iterable
    at /home/runner/work/GitHubGraduation-2021/GitHubGraduation-2021/.github/workflows/src/index.js:54:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/runner/work/GitHubGraduation-2021/GitHubGraduation-2021/.github/workflows/src/index.js:48:19
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2461) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2461) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by renz45** [comment] 2021-05-12 15:31
Sorry about that! This should be fixed now 😄  Thanks for the issue!

**Closed by renz45** 2021-05-12 15:31 UTC
